export const English = {
  heading1: "CORONA RISK CALCULATOR",
  heading2: "CHECK YOURSELF FOR COVID-19",
  heading3: "This application does not provide any medical advice",
  proceedButton: "CLICK HERE TO PROCEED",
  disclaimer:
    "Any content accessed through this website is for informaitional purpose only and is not intended to constitute professional medical advice, diagnosis or treatment. We are no way responsible for your use of this website, or for any information you receive from this website. You acknowledge that when using this website you do so at your own choice and in agreement of this disclaimer. Seek immediate medical assistance or call your doctor for all medical emergencies.",
  selectCity: "Select State, District, City",
  loadingCities: "Loading Cities..",
  howOld: "How Old Are You?",
  selectGender: "Select Gender",
  next: "Next",
  state: "State",
  district: "District",
  city: "City",
  male: "Male",
  female: "Female",
  other: "Other",
  question2Heading: "Do you have a history of any of the conditions?",
  diabetes: "Diabetes",
  heartDisease: "Heart Disease",
  bloodPressure: "High Blood Pressure",
  kidneyLiver: "Kidney or Liver Disease",
  noneOfTheAbove: "None of the above",
  acceptAndContinue: "Accept and Continue",
  disclaimerHeading: "Disclaimer"
};

export const Hindi = {
  heading1: "Corona आशंका कैलकुलेटर",
  heading2: "खुद को Corona के लिए जाँचें",
  heading3: "यह एप्लिकेशन कोई चिकित्सा सलाह प्रदान नहीं करता है",
  proceedButton: "आगे बढ़ने के लिए क्लिक करें",
  disclaimer:
    "वेबसाइट के माध्यम से ली गई कोई भी सामग्री केवल सूचनात्मक उद्देश्यों के लिए है, और इसका उद्देश्य व्यावसायिक चिकित्सा सलाह, निदान या उपचार का गठन करना नहीं है। आपके वेबसाइटों के उपयोग के लिए या वेबसाइट से प्राप्त किसी भी जानकारी के लिए किसी भी तरह से हम जिम्मेदार नहीं है। आप स्वीकार करते हैं कि वेबसाइटों का उपयोग करते समय आप अपनी सहमति से और इस अस्वीकरण के साथ समझौता करते हैं | वेबसाइटों के माध्यम से जानकारी प्राप्त करने के कारण पेशेवर चिकित्सा सलाह प्राप्त करने में देरी या उपेक्षा न करें। तत्काल चिकित्सा सहायता लें या अपने चिकित्सक को सभी चिकित्सा आपात स्थितियों के लिए बुलाएं",
  selectCity: "राज्य, जिला, शहर चुनें",
  loadingCities: "Loading शहर..",
  howOld: "आपकी उम्र क्या है ?",
  selectGender: "लिंग चुनें",
  next: "आगे",
  state: "राज्य",
  district: "जिला",
  city: "शहर",
  male: "पुरुष",
  female: "महिला",
  other: "अन्य",
  question2Heading: "क्या आपको निम्नलिखित रोग में से कोई रोग है?",
  diabetes: "मधुमेह",
  heartDisease: "दिल की बीमारी",
  bloodPressure: "उच्च रक्त चाप",
  kidneyLiver: "किडनी या लीवर की बीमारी",
  noneOfTheAbove: "इनमे से कोई भी नहीं",
  acceptAndContinue: "स्वीकार करें और जारी रखें",
  disclaimerHeading: "अस्वीकरण (Disclaimer)"
};
