export const English = {
  heading1: "CORONA RISK CALCULATOR",
  heading2: "CHECK YOURSELF FOR COVID-19",
  heading3: "This application does not provide any medical advice",
  proceedButton: "CLICK HERE TO PROCEED",
  disclaimer:
    "Any content accessed through this website is for informational purpose only and is not intended to constitute professional medical advice, diagnosis or treatment. Information is gathered and shared from reputable sources. Corona risk calculator is not responsible for errors or omissions in reporting or explanation. The website gives no assurance or warranty regarding the accuracy, timelines or applicability or the content. You acknowledge that while using this website you do so at your own risk and in agreement of this disclaimer. Seek immediate medical assistance or call the health care department for medical emergencies.",
  selectCity: "Select State, District, City",
  loadingCities: "Loading Cities..",
  howOld: "How Old Are You?",
  selectGender: "Select Gender",
  next: "Next",
  state: "State",
  district: "District",
  city: "City",
  male: "Male",
  female: "Female",
  other: "Other",
  question2Heading:
    " Do you have a history of any of the conditions mentioned below?",
  diabetes: "Diabetes",
  heartDisease: "Heart Disease",
  bloodPressure: "High Blood Pressure",
  kidneyLung: "Kidney or Lung Disease",
  noneOfTheAbove: "None of the above",
  acceptAndContinue: "Accept and Continue",
  disclaimerHeading: "Disclaimer",
  question3Heading: "Have you travelled internationally in feb/ march 2020?",
  yes: "Yes",
  no: "No",
  dryCough: "Dry Cough",
  soreThroat: "Sore Throat",
  lossOfSmell: "Loss in Sense of Smell",
  weakness: "Weakness",
  changeAppetite: "Change in appetite",
  severeCough: "Moderate to Severe Cough",
  difficultyInBreathing: "Difficulty in breathing",
  drowsiness: "Drowsiness",
  painInChest: "Persistent Pain in chest",
  severeWeakness: "Severe Weakness",
  question4Heading: "Are you experiencing any of the symptoms below?",
  question5Heading:
    "Let us know your body temperature? (Normal Temp: 98.6°F (37°C))",
  tempOption1: "Normal ( 96-98.6) °F",
  tempOption2: "Fever ( 98.6-102) °F",
  tempOption3: "High Fever ( >102) °F",
  question5Heading2:
    "Have you come in contact with anyone who has been positively tested for COVID-19 (Corona Virus)?",
  dontKnow: "Don't Know",
  resultButton: "TAP TO SEE RESULT",
  lowRisk: "LOW RISK",
  moderate: "MODERATE",
  moderateRisk: "Moderate Risk",
  highRisk: "HIGH RISK",
  smallDisclamier: "This is not a medical advice",
  basedOnAssessment1: "Based on the assessment you are at ",
  ofCovid: " of COVID-19.",
  basedOnAssessment2: "Check again after 24 hours to reassess yourself.",
  reAssess: "Re-assess",
  shareResult: "Share Result",
  shareOn: "Share On",
  block2Heading: "Precautionary Measure For You",
  block2Point1:
    " Wash your hands Regularly for 20 seconds with soap and water or alcohol-based hand rub.",
  block2Point2:
    "Cover you nose and mouth with a disposable tissue or flexed elbow when you cough or sneeze.",
  block2Point3:
    "Avoid close contact (1 meter to 3 feet) with people who are unwell.",
  block2Point4:
    "Stay Home and self isolate from others in the household if you feel unwell",
  forAnyEmergency: "For Any Emergency",
  helpline: "Helpline",
  tollFreeNumber: "Toll Free Number",
  helpLineEmail: "Email",
  iAmAt: "I am at ",
  shareString:
    ". Are you at Risk? Know if you're safe from Corona or not? | Corona Risk Calculator | Check yours at : ",
  par: "",
  alerts: "ALERTS",
  block3Point1:
    "In case your symptoms change, please contact any healthcare facility near you or",
  call: "call",
  inCaseYouSuspect: "In case you suspect a postive case, please",
  findAllHelpline:
    "or report nearby health care facility. Find all help line numbers here :",
  allHelplineLink: "all helpline numbers",
  block4Heading: "HELP AND SUPPORT",
  block4SubHeading: "Government is welcoming donations to help this cause.",
  learnMore: "Learn More",
  block5Heading: "SUBSCRIBE NEWSLETTER",
  block5SubHeading:
    "Be the first to know, discover the story. Sign up to our newsletter",
  subscribe: "Subscribe",
  yaySubscribed: "Yayy!! You have been subscribed.",
  checkMailBox: "Check your mail box.",
  rateUs: "RATE US",
  thankYou: "Thanks For Rating Us",
  reRate: "Rerate",
  checkLiveUpdates: "Check Live Updates",
  submit: "SUBMIT",
  testingfacilities: "Testing Facilities",
  youAreAt: "You are at:  ",
  consultPhysician:
    " ! Consult a Physician and find your nearest testing facility here : ",
  clickHere: "Click Here",
  precautionaryMeasuresVideo: "Precaution Measures Video",
  back: "Back",
  prev: "Prev"
};

export const Hindi = {
  heading1: "Corona आशंका कैलकुलेटर",
  heading2: "खुद को Corona के लिए जाँचें",
  heading3: "यह एप्लिकेशन कोई चिकित्सा सलाह प्रदान नहीं करता है",
  proceedButton: "आगे बढ़ने के लिए क्लिक करें",
  disclaimer:
    "इस वेबसाइट के माध्यम से अभिगम की गई कोई भी विचार/सूचना/प्रकरण केवल सूचनात्मक उद्देश्य के लिए है और इसका उद्देश्य व्यावसायिक चिकित्सा सलाह, निदान या उपचार का गठन करना नहीं है। प्रतिष्ठित स्रोतों से जानकारी एकत्र और साझा की जाती है। कोरोना आशंका कैलकुलेटर रिपोर्टिंग या स्पष्टीकरण में त्रुटियों या चूक के लिए जिम्मेदार नहीं है। वेबसाइट सटीकता, समय सीमा या प्रयोज्यता या सामग्री के बारे में कोई आश्वासन या वारंटी नहीं देती है। आप स्वीकार करते हैं कि इस वेबसाइट का उपयोग करते समय आप अपने जोखिम पर और इस अस्वीकरण के समझौते में ऐसा करते हैं। चिकित्सा आपात स्थिति के लिए तत्काल चिकित्सा सहायता लें या स्वास्थ्य विभाग को सूचित करें।",
  selectCity: "राज्य, जिला, शहर चुनें",
  loadingCities: "Loading शहर..",
  howOld: "आपकी उम्र क्या है ?",
  selectGender: "लिंग चुनें",
  next: "आगे",
  state: "राज्य",
  district: "जिला",
  city: "शहर",
  male: "पुरुष",
  female: "महिला",
  other: "अन्य",
  question2Heading: "क्या आपको निम्नलिखित रोग में से कोई रोग है?",
  diabetes: "मधुमेह",
  heartDisease: "दिल की बीमारी",
  bloodPressure: "उच्च रक्त चाप",
  kidneyLung: "किडनी या फेफड़ों की बीमारी",
  noneOfTheAbove: "इनमे से कोई भी नहीं",
  acceptAndContinue: "स्वीकार करें और जारी रखें",
  disclaimerHeading: "अस्वीकरण (Disclaimer)",
  question3Heading:
    "क्या आपने फरवरी / मार्च 2020 में अंतरराष्ट्रीय स्तर पर यात्रा की है?",
  yes: "हाँ",
  no: "नहीं",
  dryCough: "सूखी खांसी",
  soreThroat: "गले में खराश",
  lossOfSmell: "गंध की कमी",
  weakness: "कमज़ोरी",
  changeAppetite: "भूख में बदलाव",
  severeCough: "मध्यम या तीव्र खांसी",
  difficultyInBreathing: "सांस लेने में दिक्कत",
  drowsiness: "तंद्रा (सुस्ती)",
  painInChest: "सीने में लगातार दर्द",
  severeWeakness: "तीव्र कमजोरी",
  question4Heading: "क्या आप  निम्नलिखित किसी भी लक्षण को अनुभव कर रहे हैं?",
  question5Heading:
    "कृपया बताएं कि आपके शरीर का तापमान कितना है (शरीर का सामान्य तापमान 98.6°F (37°C) होता है )",
  tempOption1: "सामान्य ( 96-98.6) °F",
  tempOption2: "बुखार ( 98.6-102) °F",
  tempOption3: "तेज बुखार ( >102) °F",
  question5Heading2:
    "क्या आप किसी ऐसे व्यक्ति के संपर्क में आए हैं जिसे COVID-19 (Corona) के लिए सकारात्मक रूप से परीक्षण किया गया है?",
  dontKnow: "पता नहीं",
  resultButton: "परिणाम देखें",
  lowRisk: "कम आशंका",
  moderate: "मध्यम",
  moderateRisk: "मध्यम आशंका",
  highRisk: "उच्च आशंका",
  smallDisclamier: "यह एक चिकित्सा सलाह नहीं है",
  basedOnAssessment1: "मूल्यांकन के आधार पर आप कोविद -19 के ",
  ofCovid: " में हैं",
  basedOnAssessment2:
    "परिवर्तनों को ट्रैक करने के लिए हर 24 घंटे के बाद जांच करें",
  reAssess: "फिर से करें",
  shareResult: "परिणाम शेयर करें",
  shareOn: "शेयर",
  block2Heading: "सावधानी बरतने के उपाय",
  block2Point1: "साबुन और पानी या एल्कोहल आधारित सेनेटिसर द्वारा हाथ धोना.",
  block2Point2: "रूमाल या  कोहनी से खांसने अथवा छींकने पर नाक और मुंह ढकें.",
  block2Point3: "निकट संपर्क से बचें और सबके साथ 1 मीटर की दूरी बनाए रखें",
  block2Point4:
    "कम से कम 14 दिनों के लिए प्रभावित देशों या स्थानों  का यात्रा करने वाले व्यक्तियों से दूरी बनाए रखें",
  forAnyEmergency: "आपातकालीन परिस्थिति में",
  helpline: "हेल्पलाइन",
  tollFreeNumber: "टोल फ्री नंबर",
  helpLineEmail: "ईमेल",
  iAmAt: "मैं हूं",
  shareString:
    "क्या आप जोखिम में हैं? जानिए कि आप कोरोना से सुरक्षित हैं या नहीं। अपनी जाँच करें :",
  par: "पर. ",
  alerts: "चेतावनी",
  block3Point1:
    "यदि आपके लक्षण बदल जाते हैं, तो कृपया अपने आस-पास की किसी भी स्वास्थ्य सुविधा से संपर्क करें",
  call: "कॉल करें :",
  inCaseYouSuspect: " यदि आपको परिणाम पॉजिटिव लगता  है, तो कृपया",
  findAllHelpline:
    "या स्वास्थ्य सुविधा को रिपोर्ट करें. पूर्ण भारत के हेल्पलाइन मोबाइल नंबर :",
  allHelplineLink: "हेल्पलाइन मोबाइल नंबर",
  block4Heading: "सहायता और समर्थन",
  block4SubHeading: "इस कार्य में सरकार की सहायता हेतु दान करे।",
  learnMore: "अधिक जानें",
  block5Heading: "न्यूज़लेटर प्राप्त करें",
  block5SubHeading:
    "कहानी जानने वाले पहले व्यक्ति बनें। हमारे न्यूज़लेटर के लिए साइनअप करें",
  subscribe: "सदस्यता लें",
  yaySubscribed: "Yayy !! आप सदस्यता ले चुके हैं।",
  checkMailBox: "अपना मेलबॉक्स जांचें।",
  rateUs: "हमें रेटिंग दें",
  thankYou: "रेटिंग के लिए धन्यवाद",
  reRate: "रेटिंग बदलें",
  checkLiveUpdates: "देखिये लाइव अपडेट",
  submit: "सब्मिट",
  testingfacilities: "परीक्षण सुविधा",
  youAreAt: "परिणाम है ",
  consultPhysician:
    "| एक चिकित्सक से परामर्श करें और अपनी निकटतम परीक्षण सुविधा यहां पाएं: ",
  clickHere: "यहाँ क्लिक करें",
  precautionaryMeasuresVideo: "वीडियो के माध्यम से सावधानियां",
  back: "पीछे",
  prev: "पीछे"
};
